spring:
  application:
    name: group-manager
  data:
    mongodb:
      auto-index-creation: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: []
    currencyManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableCurrencyManagerClientException
      ignoreExceptions: [ ]
    attachmentStore:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableAttachmentStoreClientException
      ignoreExceptions: [ ]
    financeAdapter:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableFinanceAdapterClientException
      ignoreExceptions: [ ]

generator:
  join-code:
    length: 6
    allowUpperCaseLetter: true
    allowLowerCaseLetter: true
    allowDigit: true
    allowSpecialCharacter: false

currency-manager:
  read-timeout: 1000ms
  connect-timeout: 1000ms

attachment-store:
  read-timeout: 1000ms
  connect-timeout: 1000ms

finance-adapter:
  read-timeout: 1000ms
  connect-timeout: 1000ms
