spring:
  data:
    mongodb:
      uri: ${GROUP_MANAGER_DB_URI}

currency-manager:
  url: http://${CURRENCY_MANAGER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms

attachment-store:
  url: http://${ATTACHMENT_STORE_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms
