spring:
  data:
    mongodb:
      database: group_manager_db
      password: admin
      username: admin
      authentication-database: admin

currency-manager:
  url: postman-mock-server.com
  read-timeout: 1000ms
  connect-timeout: 1000ms
